name: Generate Powershell and README

on:
  workflow_dispatch:
  push:
    branches:
      - main
  repository_dispatch:
    types: [file-changed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy install-vsc-remote-pack.ps1
        run: |
          curl -sS https://raw.githubusercontent.com/brettjrea/GitHub_Generate_Readme/main/powershell/install-vsc-remote-pack.ps1 --output install-vsc-remote-pack.ps1
      
      - name: Combine files
        run: |
          toc=$(curl -sS https://raw.githubusercontent.com/brettjrea/GitHub_Generate_Readme/main/readme/generate-readme-table-of-contents.md)
          config=$(curl -sS https://raw.githubusercontent.com/brettjrea/GitHub_Generate_Readme/main/readme/windows-install-vscode-remote-pack.md)
          readme="$(echo -e "${toc}\n---\n${config}")"
          echo "${readme}" > readme.md

          
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Auto commit copied install-vsc-remote-pack.ps1'
